# Exported from Render on 2024-12-09T14:48:10Z
services:
- type: web
  name: nikka
  runtime: docker
  repo: https://github.com/hakisolos/nikka-md
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: SESSION_ID
    sync: false
  region: oregon
  healthCheckPath: /
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
